general:
steps:
  mtaBuild:
    buildTarget: 'CF'
  cloudFoundryDeploy:
    deployTool: 'mtaDeployPlugin'
    deployType: 'standard'   
    cloudFoundry:
      org: '82f90d5ftrial'
      space: 'dev'
      credentialsId: 'CF-jenkins-credentials-id'
      apiEndpoint: 'https://api.cf.us10.hana.ondemand.com' 